[build.environment]
  ONESIGNAL_REST_API_KEY = "os_v2_app_rtxwwwz7vradrhdqcihjb7kpk4xondg7fptenu5uzvl43ebsugqpqhvr63ydre7ehldzksqphxupwsgjsoft3doi7rc3y4ktperlfqy"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
